import type { AuroraProduct } from "@/lib/products/types"

const productImage = (fileName: string): string =>
  `/images/products/${fileName}`

export const auroraProductCatalog: AuroraProduct[] = [
  {
    id: "botanical-repair-mist",
    name: "Botanical Repair Mist",
    shortDescription:
      "A water-free botanical mist designed to refresh, hydrate, and comfort the look of stressed skin.",
    fullDescription:
      "A plant-based hydra-tonic made with botanical extracts selected to support brighter, calmer, and more hydrated-looking skin throughout the day.",
    category: "face-mist",
    tags: ["botanical", "hydrating", "soothing", "radiance"],
    image: productImage("botanical-repair-mist.jpg"),
    productUrl: "https://www.auroraorganics.co/product/botanical-repair-mist/",
    ingredientsHighlight: ["Ayurvedic botanical extracts", "plant vitamins"],
    price: "CAD $35.00",
    skinConcerns: [
      "acne",
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
      "oiliness",
      "redness",
      "sensitivity",
      "texture",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 95,
    benefits: [
      "Refreshes dehydrated skin",
      "Supports a calmer-looking complexion",
    ],
    routineSteps: ["face-mist"],
    recommendationEligible: true,
  },
  {
    id: "charcoal-detox-soap",
    name: "Charcoal Detox Soap",
    shortDescription:
      "A charcoal and clay cleansing bar for removing surface buildup and refreshing oily-looking skin.",
    fullDescription:
      "A deep-cleansing bar formulated with charcoal and clay to lift impurities and support cleaner-looking pores without positioning the result as medical treatment.",
    category: "cleanser",
    tags: ["charcoal", "clay", "deep cleanse", "pores"],
    image: productImage("charcoal-detox-soap.jpg"),
    productUrl: "https://www.auroraorganics.co/product/charcoal-detox-soap/",
    ingredientsHighlight: ["activated charcoal", "clay"],
    price: "CAD $17.00",
    skinConcerns: ["acne", "oiliness", "pores", "texture"],
    skinTypes: ["oily", "combination"],
    gender: "all",
    recommendationPriority: 82,
    benefits: [
      "Deep cleanses surface buildup",
      "Refreshes congested-looking pores",
    ],
    routineSteps: ["cleanser"],
    recommendationEligible: true,
  },
  {
    id: "detox-sandal-scrub",
    name: "Detox Sandal Scrub",
    shortDescription:
      "A sandalwood and turmeric face-and-body scrub for dull, rough-looking texture.",
    fullDescription:
      "A botanical exfoliating scrub created to lift surface buildup and leave dull or uneven-looking skin feeling smoother and refreshed.",
    category: "exfoliator",
    tags: ["sandalwood", "turmeric", "scrub", "weekly care"],
    image: productImage("detox-sandal-scrub.jpg"),
    productUrl: "https://www.auroraorganics.co/product/detox-sandal-scrub/",
    ingredientsHighlight: ["sandalwood", "turmeric", "botanical extracts"],
    price: "CAD $21.00",
    skinConcerns: ["dullness", "hyperpigmentation", "texture"],
    skinTypes: ["normal", "dry", "oily", "combination"],
    gender: "all",
    recommendationPriority: 62,
    benefits: [
      "Exfoliates surface buildup",
      "Supports smoother-looking texture",
    ],
    routineSteps: ["exfoliator"],
    recommendationEligible: true,
  },
  {
    id: "gold-serum",
    name: "Gold Serum",
    shortDescription:
      "A lightweight 23K gold serum focused on radiance, elasticity, and firmer-looking skin.",
    fullDescription:
      "A radiance serum formulated to moisturize dull-looking skin and support the appearance of firmness and elasticity as part of a consistent cosmetic routine.",
    category: "serum",
    tags: ["23K gold", "radiance", "firmness", "serum"],
    image: productImage("gold-serum.jpg"),
    productUrl: "https://www.auroraorganics.co/product/gold-serum/",
    ingredientsHighlight: ["23K gold", "botanical oils"],
    price: "CAD $30.00",
    skinConcerns: [
      "aging",
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 94,
    benefits: [
      "Supports radiant-looking skin",
      "Helps skin look supple and firm",
    ],
    routineSteps: ["treatment-serum"],
    recommendationEligible: true,
  },
  {
    id: "intensive-skin-repair-sandal-lotion",
    name: "Intensive Skin Repair Sandal Lotion",
    shortDescription:
      "A non-sticky sandalwood lotion for dry, dull, and uneven-looking skin.",
    fullDescription:
      "A moisturizing sandalwood lotion with botanical extracts created to soften dry-feeling skin and support a more even, comfortable-looking complexion.",
    category: "moisturizer",
    tags: ["sandalwood", "lotion", "softening", "tone"],
    image: productImage("intensive-skin-repair-sandal-lotion.jpg"),
    productUrl: "https://www.auroraorganics.co/product/sandal-moisturiser/",
    ingredientsHighlight: ["sandalwood", "botanical extracts"],
    price: "CAD $30.00",
    skinConcerns: [
      "dryness",
      "dullness",
      "hyperpigmentation",
      "redness",
      "texture",
    ],
    skinTypes: ["dry", "normal"],
    gender: "all",
    recommendationPriority: 76,
    benefits: ["Softens dry-feeling skin", "Supports more even-looking tone"],
    routineSteps: ["moisturizer"],
    recommendationEligible: true,
  },
  {
    id: "lavender-foaming-face-wash",
    name: "Lavender Foaming Face Wash",
    shortDescription:
      "A botanical foaming cleanser with lavender and naturally sourced salicylic acid.",
    fullDescription:
      "A daily face wash created to remove makeup, sunscreen, and surface impurities while supporting softer-feeling skin and clearer-looking pores.",
    category: "cleanser",
    tags: ["lavender", "foaming cleanser", "salicylic acid", "pores"],
    image: productImage("lavender-foaming-face-wash.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/lavender-foaming-soothing-anti-acne-cleanser/",
    ingredientsHighlight: [
      "lavender extract",
      "natural salicylic acid",
      "botanical extracts",
    ],
    price: "CAD $30.00",
    skinConcerns: [
      "acne",
      "dullness",
      "hyperpigmentation",
      "oiliness",
      "pores",
      "redness",
      "sensitivity",
      "texture",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 98,
    benefits: [
      "Cleans without a stripped feeling",
      "Supports clearer-looking pores",
    ],
    routineSteps: ["cleanser"],
    recommendationEligible: true,
  },
  {
    id: "lavender-soothing-lotion",
    name: "Lavender Soothing Lotion",
    shortDescription:
      "A shea butter and lavender lotion for dry, irritated, or blotchy-looking skin.",
    fullDescription:
      "A rich but non-greasy lotion formulated to moisturize dry-feeling skin and support a calmer, softer, and more even-looking appearance.",
    category: "moisturizer",
    tags: ["lavender", "shea butter", "soothing", "lotion"],
    image: productImage("lavender-soothing-lotion.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/lavender-soothing-lotion/",
    ingredientsHighlight: ["lavender extract", "shea butter"],
    price: "CAD $30.00",
    skinConcerns: [
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
      "redness",
      "sensitivity",
      "texture",
    ],
    skinTypes: ["dry", "normal", "sensitive-looking"],
    gender: "all",
    recommendationPriority: 92,
    benefits: [
      "Comforts dry-feeling skin",
      "Supports a calmer-looking complexion",
    ],
    routineSteps: ["moisturizer"],
    recommendationEligible: true,
  },
  {
    id: "niacinamide-neem-toner",
    name: "Niacinamide & NEEM Toner",
    shortDescription:
      "A tone-supporting toner for the look of dark spots, redness, and visible pores.",
    fullDescription:
      "A daily toner formulated to support balanced hydration and improve the appearance of uneven tone, post-breakout marks, and visible pores.",
    category: "toner",
    tags: ["niacinamide", "neem", "toner", "tone"],
    image: productImage("niacinamide-neem-toner.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/salicylic-acid-neem-toner/",
    ingredientsHighlight: ["niacinamide", "neem", "salicylic acid"],
    price: "CAD $30.00",
    skinConcerns: [
      "acne",
      "hydration",
      "hyperpigmentation",
      "oiliness",
      "pores",
      "redness",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 97,
    benefits: [
      "Supports more even-looking tone",
      "Refines the look of visible pores",
    ],
    routineSteps: ["toner"],
    recommendationEligible: true,
  },
  {
    id: "plump-lip-balm",
    name: "Plump Lip Balm",
    shortDescription:
      "An ultra-hydrating balm that moisturizes and softens dry-feeling lips.",
    fullDescription:
      "A moisturizing lip balm designed to soften dry lips and support a smoother, naturally supple appearance.",
    category: "lip-care",
    tags: ["lip balm", "hydrating", "softening"],
    image: productImage("plump-lip-balm.jpg"),
    productUrl: "https://www.auroraorganics.co/product/light-lip-balm/",
    ingredientsHighlight: ["moisturizing botanical oils"],
    price: "CAD $6.00",
    skinConcerns: ["dryness", "hydration", "texture"],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 58,
    benefits: ["Softens dry-feeling lips", "Supports a smoother lip texture"],
    routineSteps: ["lip-care"],
    recommendationEligible: true,
  },
  {
    id: "radiant-plump-lip-mask",
    name: "Radiant Plump Lip Mask",
    shortDescription:
      "An overnight lip mask for deep hydration and smoother, fuller-looking lips.",
    fullDescription:
      "An intensive overnight lip treatment formulated to moisturize dry lips and soften the appearance of fine lines.",
    category: "lip-care",
    tags: ["lip mask", "overnight", "hyaluronic acid", "shea butter"],
    image: null,
    productUrl: "https://www.auroraorganics.co/product/radiant-plump-lip-mask/",
    ingredientsHighlight: [
      "hyaluronic acid",
      "shea butter",
      "cocoa butter",
      "castor oil",
    ],
    price: null,
    skinConcerns: ["aging", "dryness", "hydration", "texture"],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 65,
    benefits: [
      "Deeply hydrates lips overnight",
      "Softens the look of lip lines",
    ],
    routineSteps: ["lip-care"],
    recommendationEligible: true,
  },
  {
    id: "radiant-plump-moisturizer-with-glutathione",
    name: "Radiant Plump Moisturizer with Glutathione",
    shortDescription:
      "An antioxidant moisturizer for hydration, radiance, and more even-looking tone.",
    fullDescription:
      "A daily moisturizer with glutathione, hyaluronic acid, vitamin C, alpha arbutin, kojic acid, and niacinamide to hydrate and support brighter-looking skin.",
    category: "moisturizer",
    tags: ["glutathione", "hyaluronic acid", "vitamin C", "brightening"],
    image: productImage("radiant-plump-moisturizer.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/radiant-plump-moisturizer/",
    ingredientsHighlight: [
      "glutathione",
      "hyaluronic acid",
      "vitamin C",
      "alpha arbutin",
      "niacinamide",
    ],
    price: "CAD $20.00",
    skinConcerns: [
      "aging",
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
      "redness",
      "texture",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 100,
    benefits: [
      "Replenishes moisture",
      "Supports brighter, more even-looking skin",
    ],
    routineSteps: ["moisturizer"],
    recommendationEligible: true,
  },
  {
    id: "radiant-plump-serum",
    name: "Radiant Plump Serum",
    shortDescription:
      "A brightening serum for dry patches, dark spots, and a dewy-looking finish.",
    fullDescription:
      "A lightweight serum created to moisturize dry-feeling areas and support improved elasticity and more even-looking tone.",
    category: "serum",
    tags: ["radiance", "tone", "elasticity", "serum"],
    image: productImage("radiant-plump-serum.jpg"),
    productUrl: "https://www.auroraorganics.co/product/radiant-plump-serum/",
    ingredientsHighlight: ["brightening botanical blend"],
    price: "CAD $30.00",
    skinConcerns: [
      "aging",
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 96,
    benefits: [
      "Supports a dewy-looking glow",
      "Improves the look of uneven tone",
    ],
    routineSteps: ["treatment-serum"],
    recommendationEligible: true,
  },
  {
    id: "radiant-plump-soap",
    name: "Radiant Plump Soap",
    shortDescription:
      "A turmeric and sandalwood cleansing bar for brighter, smoother-looking skin.",
    fullDescription:
      "An all-weather face-and-body bar that cleanses daily impurities while supporting soft, balanced, and radiant-looking skin.",
    category: "cleanser",
    tags: ["turmeric", "sandalwood", "glow bar", "daily cleanse"],
    image: productImage("radiant-plump-soap.jpg"),
    productUrl: "https://www.auroraorganics.co/product/radiant-plump-soap/",
    ingredientsHighlight: [
      "turmeric",
      "sandalwood",
      "neem",
      "shea butter",
      "vitamins A and E",
    ],
    price: "CAD $17.00",
    skinConcerns: [
      "acne",
      "dryness",
      "dullness",
      "hyperpigmentation",
      "redness",
      "sensitivity",
      "texture",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 88,
    benefits: [
      "Cleanses daily impurities",
      "Supports brighter, smoother-looking skin",
    ],
    routineSteps: ["cleanser"],
    recommendationEligible: true,
  },
  {
    id: "radiant-rose-face-mist",
    name: "Radiant Rose Face Mist",
    shortDescription:
      "A rose and hyaluronic acid mist for instant hydration and a fresh, dewy-looking glow.",
    fullDescription:
      "A lightweight, oil-free face mist with rose hydrosol and botanical extracts that refreshes skin and supports hydration, radiance, and comfort.",
    category: "face-mist",
    tags: ["rose", "hyaluronic acid", "dewy glow", "alcohol-free"],
    image: productImage("radiant-rose-face-mist.jpg"),
    productUrl: "https://www.auroraorganics.co/product/radiant-rose-face-mist/",
    ingredientsHighlight: [
      "rose hydrosol",
      "hyaluronic acid",
      "kiwi fruit water",
      "beet root extract",
    ],
    price: "CAD $13.95",
    skinConcerns: [
      "aging",
      "dryness",
      "dullness",
      "hydration",
      "hyperpigmentation",
      "pores",
      "redness",
      "sensitivity",
    ],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 91,
    benefits: ["Refreshes and hydrates", "Adds a dewy-looking glow"],
    routineSteps: ["face-mist"],
    recommendationEligible: true,
  },
  {
    id: "botanical-nutrify-hair-oil",
    name: "Botanical Nutrify Hair Oil",
    shortDescription:
      "A botanical hair oil formulated with essential oils and seven traditional herbs.",
    fullDescription:
      "A conditioning oil created to support smoother, shinier-looking hair and a nourished-feeling scalp.",
    category: "hair-care",
    tags: ["hair oil", "botanical herbs", "shine", "scalp"],
    image: productImage("botanical-nutrify-hair-oil.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/botanical-nutrify-hair-oil/",
    ingredientsHighlight: ["essential oils", "seven-herb botanical blend"],
    price: "CAD $11.83",
    skinConcerns: ["dryness"],
    skinTypes: ["all"],
    gender: "men",
    recommendationPriority: 30,
    benefits: ["Conditions dry-feeling hair", "Supports smoothness and shine"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "beard-and-hair-balm",
    name: "Beard and Hair Balm",
    shortDescription: "A conditioning balm for rough-feeling beard and hair.",
    fullDescription:
      "A grooming balm made to soften and manage dry, rough-feeling beard and hair.",
    category: "beard-care",
    tags: ["beard balm", "hair balm", "grooming"],
    image: productImage("beard-and-hair-balm.jpg"),
    productUrl: "https://www.auroraorganics.co/product/beard-and-hair-balm/",
    ingredientsHighlight: ["conditioning botanical blend"],
    price: "CAD $24.00",
    skinConcerns: ["dryness", "texture"],
    skinTypes: ["all"],
    gender: "men",
    recommendationPriority: 30,
    benefits: ["Softens rough-feeling hair", "Supports easier grooming"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "gift-for-her",
    name: "Gift For Her",
    shortDescription: "An official Aurora Organics wellness gift collection.",
    fullDescription:
      "A curated Aurora Organics gift set for general wellness gifting.",
    category: "gift-set",
    tags: ["gift set", "wellness"],
    image: productImage("gift-for-her.jpg"),
    productUrl: "https://www.auroraorganics.co/product/gift-for-her/",
    ingredientsHighlight: ["assorted Aurora Organics products"],
    price: "CAD $80.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "women",
    recommendationPriority: 0,
    benefits: ["Curated wellness gifting"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "gift-for-him",
    name: "Gift For Him",
    shortDescription: "An official Aurora Organics men’s care gift collection.",
    fullDescription:
      "A curated men’s care set containing official Aurora Organics grooming products.",
    category: "gift-set",
    tags: ["gift set", "men's care", "wellness"],
    image: productImage("gift-for-him.jpg"),
    productUrl: "https://www.auroraorganics.co/product/gift-for-him/",
    ingredientsHighlight: ["assorted Aurora Organics products"],
    price: "CAD $90.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "men",
    recommendationPriority: 0,
    benefits: ["Curated grooming and wellness gifting"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "natural-hand-sanitizer-disinfectant-spray",
    name: "Natural Hand Sanitizer / Disinfectant SPRAY",
    shortDescription: "A portable hand sanitizer and disinfectant spray.",
    fullDescription:
      "An official Aurora Organics hand-hygiene spray for on-the-go use.",
    category: "hand-care",
    tags: ["hand hygiene", "sanitizer", "spray"],
    image: productImage("natural-hand-sanitizer-spray.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/natural-hand-sanitizer-disinfectant-spray/",
    ingredientsHighlight: ["sanitizing blend"],
    price: "CAD $14.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Portable hand hygiene"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "natural-hand-senitizer-foaming",
    name: "Natural Hand Senitizer / Foaming",
    shortDescription: "An official Aurora Organics foaming hand sanitizer.",
    fullDescription:
      "A one-step foaming hand-hygiene product for portable everyday use.",
    category: "hand-care",
    tags: ["hand hygiene", "sanitizer", "foaming"],
    image: productImage("natural-hand-senitizer-foaming.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/natural-hand-senitizer-foaming/",
    ingredientsHighlight: ["sanitizing blend"],
    price: "CAD $16.50",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Portable hand hygiene"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "natural-multi-surface-cleaner",
    name: "Natural Multi-Surface Cleaner",
    shortDescription: "A plant-powered cleaner for household surfaces.",
    fullDescription:
      "An official Aurora Organics home-care cleaner made with plant-based cleaning agents.",
    category: "home-care",
    tags: ["home care", "surface cleaner", "plant-based"],
    image: productImage("natural-multi-surface-cleaner.jpg"),
    productUrl:
      "https://www.auroraorganics.co/product/natural-multi-surface-cleaner/",
    ingredientsHighlight: ["plant-based cleaning agents"],
    price: "CAD $20.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Plant-powered household cleaning"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "neem-liquid-dishwash",
    name: "Neem Liquid Dishwash",
    shortDescription: "A neem and citrus household dishwashing liquid.",
    fullDescription:
      "An official Aurora Organics home-care liquid formulated for washing dishes.",
    category: "home-care",
    tags: ["home care", "dishwash", "neem"],
    image: productImage("neem-liquid-dishwash.jpg"),
    productUrl: "https://www.auroraorganics.co/product/neem-liquid-dishwash/",
    ingredientsHighlight: ["neem", "citrus cleaning blend"],
    price: "CAD $160.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Household dish cleaning"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "skin-professional-gender-neutral-foot-care",
    name: "Skin Professional Gender-Neutral Foot Care",
    shortDescription: "A botanical foot soak for an at-home foot-care ritual.",
    fullDescription:
      "An official Aurora Organics foot soak created for a relaxing at-home care routine.",
    category: "foot-care",
    tags: ["foot soak", "foot care", "wellness"],
    image: productImage("gender-neutral-foot-care.jpg"),
    productUrl: "https://www.auroraorganics.co/product/foot-soak/",
    ingredientsHighlight: ["botanical foot-care blend"],
    price: "CAD $14.00",
    skinConcerns: ["dryness", "texture"],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Supports an at-home foot-care ritual"],
    routineSteps: [],
    recommendationEligible: false,
  },
  {
    id: "calmer-blend-and-soap",
    name: "Calmer Blend and Soap",
    shortDescription: "An Aurora Organics calming wellness blend and soap set.",
    fullDescription:
      "A general wellness product intended for aromatic and cleansing rituals.",
    category: "wellness",
    tags: ["calming", "soap", "aromatherapy"],
    image: productImage("calmer-blend-and-soap.jpg"),
    productUrl: "https://www.auroraorganics.co/product/calmer-blend-and-soap/",
    ingredientsHighlight: ["calming essential oil blend"],
    price: "CAD $30.00",
    skinConcerns: [],
    skinTypes: ["all"],
    gender: "all",
    recommendationPriority: 0,
    benefits: ["Supports a calming wellness ritual"],
    routineSteps: [],
    recommendationEligible: false,
  },
]

export const recommendationEligibleProducts = auroraProductCatalog.filter(
  (product) => product.recommendationEligible
)

export function getAuroraProductById(id: string): AuroraProduct | undefined {
  return auroraProductCatalog.find((product) => product.id === id)
}
